# Generated by Django 2.2.7 on 2019-12-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_english_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionaryquery',
            old_name='result',
            new_name='result1',
        ),
    ]
