# Generated by Django 3.0.1 on 2019-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_english_dictionary', '0004_auto_20191229_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryquery',
            name='result',
            field=models.CharField(choices=[('exist', 'exist'), ('not_exist', 'not_exist')], max_length=120),
        ),
    ]
